### ISSUE TITLE
DS: tests.schema_validation fails

### ISSUE THREAD

**Issue by randynobx** [BloomTech-Labs/underdog-devs-ds-a#246]
### Description
Schema_validation fails due to the inclusion of `sentiment` field in `RandomMenteeFeedback` (`data_generators/generators.py`).

The issue appears to have originated in PR https://github.com/BloomTech-Labs/underdog-devs-ds-a/pull/236
Relevant Jira Ticket for PR: [BL-748](https://bloomtechlabs.atlassian.net/browse/BL-748)

### Error
```bash
% python -m tests.schema_validation                                                                                                                                                                                [BL-841-ds-update-how-we-generate-uui-ds] 
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/randy/DataProjects/underdog-devs-ds-a/tests/schema_validation.py", line 43, in <module>
    validate_schemas()
  File "/Users/randy/DataProjects/underdog-devs-ds-a/tests/schema_validation.py", line 39, in validate_schemas
    validate_feedback()
  File "/Users/randy/DataProjects/underdog-devs-ds-a/tests/schema_validation.py", line 26, in validate_feedback
    assert all(
  File "/Users/randy/DataProjects/underdog-devs-ds-a/tests/schema_validation.py", line 27, in <genexpr>
    Feedback(**vars(RandomMenteeFeedback(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Feedback
sentiment
  extra fields not permitted (type=value_error.extra)
```

**Comment by randynobx** [comment]
Being addressed in upcoming pull request
